### ISSUE TITLE
Linking stage randomly stops

### ISSUE THREAD

**Issue by dfordivam** [WebGHC/ghc#11]
I have observed this many times now that the compilation stops at linking stage.

First it happened a few times during compiling the ghc libraries, while creating the wasm-cross nixpkgs (this was very annoying, as I had to restart the whole process again)

And this behavior can be easily reproduced while running the ghc testsuite. The compilation stops at the linking stage for random testcases. On recompiling / retrying it mostly works fine.

Here is a simple testsuite runner I created to run the ghc testsuite.
https://github.com/dfordivam/webghc-testsuite-runner

The occurence of this issue is particularly high with this, like 10% -20 % test cases.

**Comment by ElvishJerricco** [comment]
Ok first of all, getting the testsuites to build / run is amazing! Very nice :)

Anyway, ouch this is bad. I don't think I've ever seen this. I wonder if it's somehow specific to your machine? Or maybe the LLD in the binary cache has architecture specific machine code in it that's specific to my ryzen processor? Maybe you should try making a change to the LLD Nix expression to force it to rebuild and see if that still fails (EDIT: I guess you'd actually want to go back as far as LLVM)

**Comment by dfordivam** [comment]
It looks like LLD is having trouble working in multi-threaded mode. perhaps it reached a deadlock.

And forcing a single-threaded run works fine... may be this is a machine specific thing, so closing this at the moment..

```
[pid  2277] futex(0x7fbef6ffcdc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  2276] futex(0x7fbef77fddc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  2275] futex(0x7fbef7ffedc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  2274] futex(0x7fbefcaa2dc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  2273] futex(0x7fbefd2a3dc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  2272] futex(0x7fbefdaa4dc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  2271] futex(0x7fbefe2a5dc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  2270] futex(0x7fbefeaa6db8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  2076] futex(0x7ffda11e97c8, FUTEX_WAIT_PRIVATE, 0, NULL
```

**Comment by ElvishJerricco** [comment]
@dfordivam Can we force LLD to always run single threaded in `wasm-cross` so this stops happening for good, until someone fixes LLD?

**Comment by ElvishJerricco** [comment]
There is a `--no-threads` command line option:

```
  --no-threads           Do not run the linker multi-threaded
```

Should we always add that flag?

**Comment by dfordivam** [comment]
I added it to the cross.nix, and things are working fine now. I think its good to add it..

```
        then "--allow-undefined-file=${musl-cross}/lib/wasm.syms --no-threads"
```
